AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: food-inspection-lambda
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: s3://lambda-artifacts-33bbf03aa8a54bfe/1af5bd7ecaf26532d394cb2572f63b24
      Description: Call the AWS Lambda API or run on schedule
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
      - Ref: libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: food-inspection-lambda-nodejs-lib
      Description: Dependencies for the food-inspection-lambda
      ContentUri: s3://lambda-artifacts-33bbf03aa8a54bfe/2e0d344c175df1193aac63dafbff002b
      CompatibleRuntimes:
      - nodejs12.x
