let data = [
    {
      businessName: 'DISCO TACO',
      address: '1605 W MONTROSE AVE  CHICAGO IL 60613',
      risk: 'Risk 1 (High)', 
      riskColor: 'danger',
      location: { latitude: '-87.66949202485075', longitude: '41.96147827109243' },
      violations: undefined
    },
    {
      businessName: 'RED STAR LIQUORS',
      address: '2725-2727 N MILWAUKEE AVE  CHICAGO IL 60647',
      risk: 'Risk 2 (Medium)',
      riskColor: 'secondary',
      location: { latitude: '-87.70998753402094', longitude: '41.93078708970233' },
      violations: '57. ALL FOOD EMPLOYEES HAVE FOOD HANDLER TRAINING - Comments: NO FOOD HANDLERS CERTIFICATES ON PREMISES. INSTRUCTED MANAGER ALL FOOD HANDLERS MUST BE CERTIFIED WITH NAMES OF EMPLOYEES ON PREMISES.'
    },
    {
      businessName: 'LA FORTALEZA DE ARCELIA GUERRERO',
      address: '5958 W DIVERSEY AVE  CHICAGO IL 60639',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.7759069982422', longitude: '41.931249818095836' },
      violations: '37. FOOD PROPERLY LABELED; ORIGINAL CONTAINER - Comments: MUST PROPERLY LABEL FOOD STORAGE CONTAINERS WHEN FOOD IS NOT IN THE ORIGINAL CONTAINER. | 40. PERSONAL CLEANLINESS - Comments: OBSERVED EMPLOYEES NOT WEARING HAIR RESTRAINTS WHILE FOOD IS BEING PREPARED AND SERVED. MUST WEAR A HAIR RESTRAINT AT ALL TIMES FOOD IS BEING PREPARED AND SERVED. | 41. WIPING CLOTHS: PROPERLY USED & STORED - Comments:  OBSERVED WIPING CLOTHS STORED ON PREP COOLERS AND PREP TABLES IN FRONT FOOD PREPARATION AREA. MUST PROPERLY STORE WIPING CLOTHS IN A SANITIZER SOLUTION WHEN NOT IN USE.  | 51. PLUMBING INSTALLED; PROPER BACKFLOW DEVICES - Comments: ADDITIONAL WATER PRESSURE NEEDED AT THE HAND WASHING SINK BETWEEN PREP AREA AND DISHWASHIG AREA. MUST REPAIR AND MAINTAIN. | 51. PLUMBING INSTALLED; PROPER BACKFLOW DEVICES - Comments: ADDITIONAL WATER PRESSURE NEEDED AT THE HAND WASHING SINK BETWEEN PREP AREA AND DISHWASHIG AREA. MUST REPAIR AND MAINTAIN. | 56. ADEQUATE VENTILATION & LIGHTING; DESIGNATED AREAS USED - Comments:  OBSERVED GREASE BUILD UP ON VENTILATION HOOD ABOVE COOKING EQUIPMENT AND FILTERS. MUST CLEAN AND MAINTAIN. | 60. PREVIOUS CORE VIOLATION CORRECTED - Comments: PREVIOUS CORE VIOLATIONS NOT CORRECTED FROM INSPECTION REPORT#2285636 ON 04/23/2020 #57 OBSERVED FOOD HANDLING EMPLOYEES WITHOUT THE FOOD HANDLER TRAINING CERTIFICATE. MUST SHOW PROOF OF TRAINING FOR ALL EMPLOYEES. PRIORITY FOUNDATION 7-42-090. NO CITATION ISSUED.'
    },
    {
      businessName: 'CAFE TOLA #4',
      address: '2489 N MILWAUKEE AVE  CHICAGO IL 60647',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.70319925259288', longitude: '41.92663502691596' },
      violations: undefined
    },
    {
      businessName: 'DISCO TACO',
      address: '1605 W MONTROSE AVE  CHICAGO IL 60613',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.66949202485075', longitude: '41.96147827109243' },
      violations: '10. ADEQUATE HANDWASHING SINKS PROPERLY SUPPLIED AND ACCESSIBLE - Comments: NOTED NO HAND WASH SIGNAGE AT THE HAND WASH SINKS. INSTRUCTED TO POST HAND WASH SIGNS AT ALL HAND WASH SINKS'
    },
    {
      businessName: 'MARZ COMMINITY BREWING CO.',
      address: '1950 N WESTERN AVE  CHICAGO IL 60647',
      risk: 'Risk 3 (Low)',
      location: { latitude: '-87.68754385201615', longitude: '41.917134801370274' },
      violations: '53. TOILET FACILITIES: PROPERLY CONSTRUCTED, SUPPLIED, & CLEANED - Comments: NO COVERED TRASH RECEPTACLE IN WOMENS WASHROOM. MUST PROVIDE.'
    },
    {
      businessName: 'Jimmy Johns',
      address: '51 W DIVISION ST  CHICAGO IL 60610',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.63058113117621', longitude: '41.903806014540685' },
      violations: undefined
    },
    {
      businessName: 'SUNRISE CAFE RESTAURANT',
      address: '2012 W CHICAGO AVE  CHICAGO IL 60622',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.67763415125889', longitude: '41.8960101788438' },
      violations: '10. ADEQUATE HANDWASHING SINKS PROPERLY SUPPLIED AND ACCESSIBLE - Comments: FOUND NO HANDWASHING SIGNAGE AT REAR FOOD PREPARATION AREA. MUST PROVIDE. | 53. TOILET FACILITIES: PROPERLY CONSTRUCTED, SUPPLIED, & CLEANED - Comments: FOUND NO COVERED GARBAGE RECEPTACLE IN WOMENS OR UNISEX WASHROOM. MUST PROVIDE COVERED GARBAGE RECEPTACLE IN ALL WASHROOMS WOMEN UTILIZE.  | 55. PHYSICAL FACILITIES INSTALLED, MAINTAINED & CLEAN - Comments: FOUND AN ACCUMULATION OF GREASE UNDER FRYER. MUST CLEAN SANITIZE AND MAINTAIN.'
    },
    {
      businessName: 'LA AZTECA PALETERIA',
      address: '3018 W CERMAK RD  CHICAGO IL 60623',
      risk: 'Risk 3 (Low)',
      location: { latitude: '-87.70113231549328', longitude: '41.85193447241584' },
      violations: undefined
    },
    {
      businessName: 'CIALES POULTRY MEATS & FISH',
      address: '2141 W ARMITAGE AVE  CHICAGO IL 60647',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.68171694459953', longitude: '41.9175641969242' },
      violations: '2. CITY OF CHICAGO FOOD SERVICE SANITATION CERTIFICATE - Comments: OBSERVED EXPIRED CITY OF CHICAGO CERTIFIED FOOD MANAGER CERTIFICATE POSTED ON PREMISES. INSTRUCTED MANAGER MUST PROVIDE AND POST A VALID UNEXPIRED CITY OF CHICAGO CERTIFIED FOOD MANAGER ORIGINAL CERTIFICATE ON PREMISES. PRIORITY FOUNDATION 7-38-012. | 51. PLUMBING INSTALLED; PROPER BACKFLOW DEVICES - Comments: 1ST FLOOR 3-COMPARTMENT SINK STOPPERS (X3)NOT WORKING. INSTRUCTED MANAGER TO PROVIDE WORKING STOPPERS FOR SAID SINK.'
    },
    {
      businessName: "NICK'S ON NORTH",
      address: '3323 W NORTH AVE  CHICAGO IL 60647',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.71042949751607', longitude: '41.90995972342911' },
      violations: '3. MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL EMPLOYEE; KNOWLEDGE, RESPONSIBILITIES AND REPORTING - Comments: NO EMPLOYEE HEALTH POLICY ON PREMISES. INSTRUCTED MANAGER MUST PROVIDE AN EMPLOYEE HEALTH POLICY ON PREMISES. PRIORITY FOUNDATION 7-38-010. NO CITATION ISSUED. | 60. PREVIOUS CORE VIOLATION CORRECTED - Comments: PREVIOUS CORE VIOLATION #58 NO FOOD ALLERGEN TRAINING CERTIFICATES ON PREMISES. INSTRUCTED ALL CITY OF CHICAGO CERTIFIED FOOD MANAGERS MUST HAVE FOOD ALLLERGEN TRAINING CERTIFICATES ON PREMISES FROM REPORT #2370268 DATED ON 05/07/20 NOT CORRECTED. INSTRUCTED MANAGER SAID PREVIOUS CORE VIOLATION MUST BE CORRECTED BY DATE OF REINSPECTION. PRIORITY FOUNDATION 7-42-090. NO CITATION ISSUED.'
    },
    {
      businessName: 'CAFE TOLA I',
      address: '3612 N SOUTHPORT AVE  CHICAGO IL 60613',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.66417317539015', longitude: '41.947496136751546' },
      violations: undefined
    },
    {
      businessName: "DANNY'S MINI STORE",
      address: '5220 S PULASKI RD  CHICAGO IL 60632',
      risk: 'Risk 2 (Medium)', riskColor: 'secondary',
      location: { latitude: '-87.723443740796', longitude: '41.797991869962225' },
      violations: '3. MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL EMPLOYEE; KNOWLEDGE, RESPONSIBILITIES AND REPORTING - Comments: NO EMPLOYEE HEALTH POLICY IN PLACE. INSTD TO PROVIDE A VERIFIABLE EMPLOYEE ACKNOWLEDGED HEALTHPOLICY AND MAINTAIN ON SITE. PRIORITY FOUNDATION 7-38-010 | 5. PROCEDURES FOR RESPONDING TO VOMITING AND DIARRHEAL EVENTS - Comments:  NO PROCEDURE IN PLACE FOR RESPONDING TO VOMITING AND DIARRHEAL EVENTS. INSTD TO PROVIDE PROCEDURE AND NECESSARY SUPPLIES EFFECTIVE AGAINST NOROVIRUS. PRIORITY FOUNDATION 7-38-005  | 33. PROPER COOLING METHODS USED; ADEQUATE EQUIPMENT FOR TEMPERATURE CONTROL - Comments: PREP COOLER AT 48.5F. INSTD TO MAINTAIN AT 41F OR BELOW AT ALL TIMES. PRIORITY VIOLATION 7-38-005 | 38. INSECTS, RODENTS, & ANIMALS NOT PRESENT - Comments: NO PEST CONTROL LOGBOOK OR PROOF OF SERVICE. INSTD TO PROVIDE FROM LICENSED COMPANY AND MAINTAIN ON SITE. PRIORITY FOUNDATION 7-38-020(C)'
    },
    {
      businessName: 'Beasley CPC',
      address: '5165 S State ST  CHICAGO IL 60609',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.62569446789126', longitude: '41.80001174659164' },
      violations: "38. INSECTS, RODENTS, & ANIMALS NOT PRESENT - Comments: OBSERVED AN APPX.'1/2-3/4' GAP IN RIGHT CORNER AT DOOR #4 AND PIN HOLE IN FRONT ENTRY DOOR.MUST MAKE DOORS TIGHT FITTING. | 51. PLUMBING INSTALLED; PROPER BACKFLOW DEVICES - Comments: MUST REPAIR OR REPLACE LEAKY PIPE AT 3- COMPARTMENT SINK.MUST ADJUST FAUCET HANDLES TO STAY ON LONGER IN TOILET ROOMS IN CLASS ROOM #2,4 & 5. | 55. PHYSICAL FACILITIES INSTALLED, MAINTAINED & CLEAN - Comments: MUST ELEVATE ARTICLES OFF OF FLOOR IN HALLWAY WALL CLOSETS. | 55. PHYSICAL FACILITIES INSTALLED, MAINTAINED & CLEAN - Comments: MUST CLEAN DEBRIS FROM FLOOR IN HALLWAY WALL CLOSETS. | 55. PHYSICAL FACILITIES INSTALLED, MAINTAINED & CLEAN - Comments: MUST SEAL GAPS IN WALL NEAR RADIATORS IN CLASS ROOM #2."
    },
    {
      businessName: 'SUPERMERCADO EL TAXQUENITO',
      address: '6309 W GRAND AVE  CHICAGO IL 60639',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.78339752005009', longitude: '41.92189422993173' },
      violations: undefined
    },
    {
      businessName: 'PALETAS LA AZTECA',
      address: '3012 W CERMAK RD  CHICAGO IL 60623',
      risk: 'Risk 3 (Low)',
      location: { latitude: '-87.70089765429343', longitude: '41.85193888133392' },
      violations: undefined
    },
    {
      businessName: 'LA BONITA SUPERMARKET INC',
      address: '5257 S ASHLAND AVE  CHICAGO IL 60609',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.66453687828134', longitude: '41.79782258812668' },
      violations: "38. INSECTS, RODENTS, & ANIMALS NOT PRESENT - Comments: Violation Codes: 6-202.15 Inspector Comments: OBSERVED AN APPX.'1-2' GAP IN CENTER OF DOUBLE ENTRY DOORS.MUST MAKE DOORS TIGT FITTING. | 47. FOOD & NON-FOOD CONTACT SURFACES CLEANABLE, PROPERLY DESIGNED, CONSTRUCTED & USED - Comments: Violation Codes: 4-501.11 Inspector Comments: MUST REPAIR OR REPLACE WORN DOOR GASKETS ON MILK AND PACKAGED FOODS IN REACH IN COOLER.MUST REMOVE RUST FROM LOWER SHELF OF PREP TABLE . | 49. NON-FOOD/FOOD CONTACT SURFACES CLEAN - Comments: Violation Codes: 4-601.11(C) Inspector Comments: MUST DEFROST ICE CREAM FREEZERS. | 51. PLUMBING INSTALLED; PROPER BACKFLOW DEVICES - Comments: Violation Codes: 5-205.15 Inspector Comments: MUST REPAIR OR REPLACE LEAKY CONNECTION AT TOILET. | 55. PHYSICAL FACILITIES INSTALLED, MAINTAINED & CLEAN - Comments: Violation Codes: 6-201.13 Inspector Comments: MUST REPAIR OR REPLACE DAMAGED UPPER WALL IN TOILET ROOM. | 58. ALLERGEN TRAINING AS REQUIRED - Comments: Violation Codes: 2-102.13 Inspector Comments: OBSERVED NO FOOD ALLERGEN TRAINING FOR FOOD MANAGER.MUST PROVIDE AND MAINTAIN"
    },
    {
      businessName: 'WESTTOWN TAQUERIA',
      address: '1760 W CHICAGO AVE  CHICAGO IL 60622',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.67211594992528', longitude: '41.89610267284695' },
      violations: undefined
    },
    {
      businessName: 'ANTOJITOS GUATEMALTECOS',
      address: '5823 W FULLERTON AVE  CHICAGO IL 60639',
      risk: 'Risk 1 (High)', riskColor: 'danger',
      location: { latitude: '-87.77191442640833', longitude: '41.923777505298624' },
      violations: undefined
    },
    {
      businessName: 'CLUB NUTRICION LIA',
      address: '3720 W 26TH ST  CHICAGO IL 60623',
      risk: 'Risk 2 (Medium)', riskColor: 'secondary',
      location: { latitude: '-87.71821191334412', longitude: '41.84444353922239' },
      violations: undefined
    }
  ]

export default data;